tieba:
  #支持多个逗号分隔开
  tiebaName: 李毅,健身,wow,图解电影,腹肌,摄影
  tiebaTopUrl: http://tieba.baidu.com/f/like/furank?ie=utf-8&kw=
  tiebaContentUrl: http://tieba.baidu.com/f?ie=utf-8&kw=
  tiebaContentPageUrl: http://tieba.baidu.com/p/
  #1*50=50个帖子 每次只抓第一页帖子
  tiebaContentPageEndNum: 1
  tiebaImageUrl: https://imgsa.baidu.com/forum/w%3D580/
  tiebaContentIdTopic: tieba_content_id_topic
  tiebaContentNoImageIdTopic: tieba_content_noimage_id_topic
  #我们可以通过java -DexecuteDeleteTiebaImageTask="fase" 修改启动参数
  executeDeleteTiebaImageTask: true
spring:
  redis:
    database: 2
    host: 47.94.111.150
    password: gaoguangjin
    pool.max-active: 50000
    pool.max-idle: 500
    pool.max-wait: 1000
    pool.min-idle: 300
    port: 6379
    timeout: 100000
  datasource:
      name: database
      #url: jdbc:mysql://110.173.28.188:3306/master?useUnicode=true&characterEncoding=utf-8
      #username: slave
      #password: mobile
      url: jdbc:mysql://123.56.118.135:3306/master?useUnicode=true&characterEncoding=utf-8
      username: mobile
      password: mobile
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQueryTimeout: 900000
      validationQuery: SELECT SYSDATE() from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

qiniu:
  accessKey: Bip6vCz50yIiMGjecwhvbRXluTP9XVWr8_NaA9Py
  secretKey: f3KjUz5LUjbscU-FG-pyk_qkYTCyah25qS9WFmZW
  #ggj2010 ggjqn
  bucketName: product
  domain: http://ocg3iebmc.bkt.clouddn.com/
